spring:
  #quartz config
#  quartz:
#    job-details:
#      myJob:
#        durability: true
#        job-class: com.victor.alertAssign.job.AlertAssignJob
#      triggers:
#        myTrigger:
#          cron: 0 0 7 ? * MON
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 50
        show_sql: false
        format_sql: true
        default_schema: it
    show-sql: false
#logging:
#  level:
#    root: info

  mail:
    host: smtp.gmail.com
    port: 465
    username: victor01.santos@catolicasc.org.br
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
