spring:
  #quartz config
#  quartz:
#    job-details:
#      myJob:
#        durability: true
#        job-class: com.victor.alertAssign.job.AlertAssignJob
#      triggers:
#        myTrigger:
#          cron: 0 0 7 ? * MON
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 50
        show_sql: false
        format_sql: true
    show-sql: false
#logging:
#  level:
#    root: info
