name: Deploy AlertAssign

on:
  push:
    branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v3

          - name: Setup Java
            uses: actions/setup-java@v3
            with:
              distribution: 'temurin'
              java-version: 17

          - name: Build project
            run: mvn clean install

          - name: Login DockerHub
            run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          - name: Build Docker image
            run: docker build -t vicjll/alert_assign .
          - name: Push Docker image
            run: docker push vicjll/alert_assign