name: Deploy AlertAssign

on:
    push:
      branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Build project
              run: mvn clean install -DskipTests

            - name: Login DockerHub
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Docker image
              run: docker build -t vicjll/alert_assign .
            - name: Push Docker image
              run: docker push vicjll/alert_assign

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull img form docker hub
              run: docker pull vicjll/alert_assign:latest
            - name: Remove docker cotainer
              run: docker rm -f alert_assign_container
            - name: Run docker container
              run: docker run -d -p 8080:8080 -e DATABASE_USERNAME=${secrets.DATABASE_USERNAME} -e DATABASE_PASSWORD=${secrets.DATABASE_PASSWORD} -e DATABASE_URL=${secrets.DATABASE_URL} --name alert_assign_container vicjll/alert_assign