name: Deploy AlertAssign

on:
    push:
      branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Build project
              run: mvn clean install -DskipTests
              env:
                DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
                DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                DATABASE_URL: ${{ secrets.DATABASE_URL }}

            - name: Login DockerHub
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build Docker image
              run: docker build -t vicjll/alert_assign .
            - name: Push Docker image
              run: docker push vicjll/alert_assign

    deploy:
      needs: build
      runs-on: self-hosted
      steps:

        - name: Stop container named alert_assign_container
          run: |
            if [ "$(docker ps a -q --filter 'name=alert_assign_container')" ]; then
              docker stop alert_assign_container
            fi

        - name: Remove all containers if any
          run: |
            if [ "$(docker ps a -q --filter 'name=alert_assign_container')" ]; then
              docker rm alert_assign_container
            fi

        - name: Remove all images if any
          run: |
            if [ "$(docker images -q --filter 'reference=vicjll/alert_assign')" ]; then
              docker rmi vicjll/alert_assign
            fi

        - name: Pull img from Docker Hub
          run: docker pull vicjll/alert_assign:latest

        - name: Run Docker container
          run: |
            docker run -d -p 8080:8080 \
            -e DATABASE_USERNAME="${{ secrets.DATABASE_USERNAME }}" \
            -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e MAIL_PASS="${{ secrets.MAIL_PASS }}" \
            --name alert_assign_container vicjll/alert_assign
